name: build-doc-ximage
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - ximage
  - pandoc
  - pre-commit
  - nbsphinx==0.9.3
  - sphinx==5.1.1
  - sphinx-book-theme==1.1.0
  - sphinx-mdinclude==0.5.3
  - sphinx-gallery


